### ISSUE TITLE
When will continue to use it in vscode

### ISSUE THREAD

**Issue by CG-man** [CodeMooseUS/vscode-devtools#13]
![image](https://user-images.githubusercontent.com/12809498/49077760-1577c180-f277-11e8-9d1c-4dc136804087.png)

**Comment by CodeMooseUS** [comment]
Unfortunately one of the npm packages I used in the project had a dependency on another package which was recently discovered to contain malicious code. Once I found out, I took the appropriate action and removed that dependency from my extension. 

I have submitted a new update to the vscode marketplace (v0.0.5) with the package removed and am just waiting on vscode to verify the update and remove my extension from their blocklist. 

You can read a bit more about what happened to my extension and several others, in the official vscode blog here:

https://code.visualstudio.com/blogs/2018/11/26/event-stream

**Comment by andysterland** [comment]
The updated version of the extension has been pushed to the store and everyone should be able to use it.
