### ISSUE TITLE
No dropdown to select Chrome instance

### ISSUE THREAD

**Issue by maharielrosario** [CodeMooseUS/vscode-devtools#16]
When I click DevTools for Chrome: Attach to a target, nothing happens.

**Comment by KennyVL** [comment]
Been searching forever on how to start using DevTools. Installed and uninstalled dozens of times. Now I see I'm not the only one having this issue. Did this ever get follow-up?

**Comment by BlankSourceCode** [comment]
Did you launch chrome using the `--remote-debugging-port=9222` command line argument? If not, there won't be any debuggable instances of chrome running, so the attach list won't populate.

I've added an error message for this case in version #0.0.6 of the extension
