### ISSUE TITLE
problem in mac

### ISSUE THREAD

**Issue by codigoart** [CodeMooseUS/vscode-devtools#19]
hello i can't get this to work in both methodes , does this works in macos catalina ?

**Comment by zyrong** [comment]
Neither can i

**Comment by KennyVL** [comment]
Same here. I can launch Chrome from the plugin but don't get the target selection

**Comment by BlankSourceCode** [comment]
Try with version #0.0.6 of the extension, it should hopefully be fixed now.

**Comment by SergiArias** [comment]
It works for me in mac catalina. I am using chromium though.

**Comment by ZeroPie** [comment]
Can confirm neither chrome nor Chromium Work on Mac Os Catalina, commands used:

```
/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --remote-debugging-port=9222
```
```
/Applications/Chromium.app/Contents/MacOS/Chromium --remote-debugging-port=9222
```

```
Could not find any targets for attaching. Did you remember to run Chrome with '--remote-debugging-port=9222'?
```
