### ISSUE TITLE
problem in linux (ubuntu)

### ISSUE THREAD

**Issue by uundedd** [CodeMooseUS/vscode-devtools#20]
in linux 
open an empty devtools tab in vscode after choose target

**Comment by justinforlenza** [comment]
+1 I am having the same issues on Kubuntu 20.04

**Comment by codeunifier** [comment]
Same issue here, also on Kubuntu 20.04. Tried running with a clean instance of Chrome and no extensions installed, also tried using the --disable-extensions flag. Neither produced any results, just an empty devtools tab. It does seem to be recognizing the url, as a false url does produce an error message, there just isn't anything rendering in the view.
