### ISSUE TITLE
Dev Tools when coming up empty

### ISSUE THREAD

**Issue by billkamm-nuix** [CodeMooseUS/vscode-devtools#30]
I saw a closed issue about this in the release log, but I'm running the latest version of VS Code and this issue is still occurring for me.  The Dev Tools window opens, but it is completely empty.

![image](https://user-images.githubusercontent.com/65233871/99812333-53311d00-2b14-11eb-96e1-1fe617ff4923.png)

![image](https://user-images.githubusercontent.com/65233871/99812401-6b08a100-2b14-11eb-85e0-c1e0dc0fe3e8.png)

![image](https://user-images.githubusercontent.com/65233871/99812425-75c33600-2b14-11eb-93f9-16357cbb3aff.png)

![image](https://user-images.githubusercontent.com/65233871/99812556-9c816c80-2b14-11eb-9af5-2a022bf285e8.png)

**Comment by 0104910052** [comment]
Same here, did you find any workaround maybe?

**Comment by A1-exe** [comment]
This still appears to be a problem

**Comment by chrisjallen** [comment]
still getting this :(

**Comment by ezdub** [comment]
I had this issue as well; can see and select my devtools instances to attach to but DevTools comes up empty

**Comment by kover** [comment]
Same here macOS 11.5, Chrome 92.0.4515.131 

**VSCode**
  Version: 1.59.0 (Universal)
  Commit: 379476f0e13988d90fab105c5c19e7abc8b1dea8
  Date: 2021-08-04T23:14:40.191Z
  Electron: 13.1.7
  Chrome: 91.0.4472.124
  Node.js: 14.16.0
  V8: 9.1.269.36-electron.0
  OS: Darwin x64 20.6.0

No errors in the VSC Developer Tools
